/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: d7dc7446a98d853e7d1ca882ad30d44a)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/mcp-gateway.worker");
		durableNamespaces: "MCPGatewayInstance";
	}
	interface DevEnv {
		HYPERDRIVE: Hyperdrive;
		MCP_GATEWAY_ANALYTICS: AnalyticsEngineDataset;
		ENVIRONMENT: "development";
		APP_BASE_URL: "http://localhost:3000";
		MCP_GATEWAY_BASE_URL: "http://localhost:8806";
		SUPPORTED_SCOPES: "profile";
		GATEWAY_ACCESS_TOKEN_TTL_SECONDS: "900";
		AUDIT_RETENTION_DAYS: "60";
		UPSTREAM_REQUIRE_HTTPS: "true";
		MCP_GATEWAY_JWT_ISSUER: "http://localhost:3000";
		MCP_GATEWAY_JWT_PUBLIC_KEYSET_JSON: string;
		MCP_GATEWAY_CREDENTIAL_KEYSET_JSON: string;
		MCP_GATEWAY_RATE_LIMIT_SECRET: string;
		MCP_GATEWAY_INSTANCE: DurableObjectNamespace<import("./src/mcp-gateway.worker").MCPGatewayInstance>;
	}
	interface Env {
		HYPERDRIVE: Hyperdrive;
		MCP_GATEWAY_ANALYTICS: AnalyticsEngineDataset;
		ENVIRONMENT: "development" | "production";
		APP_BASE_URL: "http://localhost:3000" | "https://app.kilo.ai";
		MCP_GATEWAY_BASE_URL: "http://localhost:8806" | "https://mcp.kilosessions.ai";
		SUPPORTED_SCOPES: "profile";
		GATEWAY_ACCESS_TOKEN_TTL_SECONDS: "900";
		AUDIT_RETENTION_DAYS: "60";
		UPSTREAM_REQUIRE_HTTPS: "true";
		MCP_GATEWAY_JWT_ISSUER: "http://localhost:3000" | "https://app.kilo.ai";
		MCP_GATEWAY_JWT_PUBLIC_KEYSET_JSON: string;
		MCP_GATEWAY_CREDENTIAL_KEYSET_JSON: string;
		MCP_GATEWAY_RATE_LIMIT_SECRET: string;
		MCP_GATEWAY_INSTANCE: DurableObjectNamespace<import("./src/mcp-gateway.worker").MCPGatewayInstance>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "APP_BASE_URL" | "MCP_GATEWAY_BASE_URL" | "SUPPORTED_SCOPES" | "GATEWAY_ACCESS_TOKEN_TTL_SECONDS" | "AUDIT_RETENTION_DAYS" | "UPSTREAM_REQUIRE_HTTPS" | "MCP_GATEWAY_JWT_ISSUER" | "MCP_GATEWAY_JWT_PUBLIC_KEYSET_JSON" | "MCP_GATEWAY_CREDENTIAL_KEYSET_JSON" | "MCP_GATEWAY_RATE_LIMIT_SECRET">> {}
}
