/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface CloudflareBindings` (hash: 0f37de76f6c360a7474c52a720a959c5)
interface __BaseEnv_CloudflareBindings {
	USER_EXISTS_CACHE: KVNamespace;
	SESSION_INGEST_R2: R2Bucket;
	HYPERDRIVE: Hyperdrive;
	INGEST_QUEUE: Queue;
	NEXTAUTH_SECRET_PROD: SecretsStoreSecret;
	INTERNAL_API_SECRET_PROD: SecretsStoreSecret;
	DIRECT_INGEST_PERCENT: "0";
	DIRECT_INGEST_USER_IDS: "";
	DIRECT_INGEST_MAX_BYTES: "4194304";
	SESSION_INGEST_DO: DurableObjectNamespace<import("./src/index").SessionIngestDO>;
	SESSION_ACCESS_CACHE_DO: DurableObjectNamespace<import("./src/index").SessionAccessCacheDO>;
	USER_CONNECTION_DO: DurableObjectNamespace<import("./src/index").UserConnectionDO>;
	O11Y: Fetcher /* o11y */;
	NOTIFICATIONS: Service /* entrypoint NotificationsService from notifications */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "SessionIngestDO" | "SessionAccessCacheDO" | "UserConnectionDO";
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DIRECT_INGEST_PERCENT" | "DIRECT_INGEST_USER_IDS" | "DIRECT_INGEST_MAX_BYTES">> {}
}
declare module "*.sql" {
	const value: string;
	export default value;
}
