/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: bab8c3c4c1ce0d7b7b5498e9e2918d9d)
interface __BaseEnv_Env {
	AUTO_ROUTING_CONFIG: KVNamespace;
	HYPERDRIVE: Hyperdrive;
	AUTO_ROUTING_CLASSIFIER_METRICS_V2: AnalyticsEngineDataset;
	INTERNAL_API_SECRET_PROD: SecretsStoreSecret;
	OPENROUTER_API_KEY: SecretsStoreSecret;
	O11Y_CF_AE_API_TOKEN: SecretsStoreSecret;
	O11Y_CF_ACCOUNT_ID: "e115e769bcdd4c3d66af59d3332cb394";
	AUTO_ROUTING_DECISION_CACHE: DurableObjectNamespace<import("./src/index").AutoRoutingDecisionCacheDO>;
	BENCHMARK_SERVICE: Fetcher /* auto-routing-benchmark */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "AutoRoutingDecisionCacheDO";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "O11Y_CF_ACCOUNT_ID">> {}
}
