export const TOOL_CGROUP_MODE_ENV = 'TOOL_CGROUP_MODE';
export const TOOL_CGROUP_RESERVE_MB_ENV = 'TOOL_CGROUP_RESERVE_MB';
export const TOOL_CGROUP_SERVER_LIMIT_MB_ENV = 'TOOL_CGROUP_SERVER_LIMIT_MB';
export const TOOL_CGROUP_SWEEP_INTERVAL_MS_ENV = 'TOOL_CGROUP_SWEEP_INTERVAL_MS';
export const TOOL_CGROUP_OOM_GROUP_ENV = 'TOOL_CGROUP_OOM_GROUP';
export const TOOL_CGROUP_CPU_WEIGHT_ENV = 'TOOL_CGROUP_CPU_WEIGHT';
export const TOOL_CGROUP_SERVER_CPU_WEIGHT_ENV = 'TOOL_CGROUP_SERVER_CPU_WEIGHT';

export const TOOL_CGROUP_ENV_KEYS = [
  TOOL_CGROUP_MODE_ENV,
  TOOL_CGROUP_RESERVE_MB_ENV,
  TOOL_CGROUP_SERVER_LIMIT_MB_ENV,
  TOOL_CGROUP_SWEEP_INTERVAL_MS_ENV,
  TOOL_CGROUP_OOM_GROUP_ENV,
  TOOL_CGROUP_CPU_WEIGHT_ENV,
  TOOL_CGROUP_SERVER_CPU_WEIGHT_ENV,
] as const;

export type ToolCgroupEnvKey = (typeof TOOL_CGROUP_ENV_KEYS)[number];
export type ToolCgroupEnv = Partial<Record<ToolCgroupEnvKey, string>>;
