/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 6f3adb06d0aa774c176b3daf114133b6)
interface __BaseEnv_Env {
	HYPERDRIVE: Hyperdrive;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
